name: Deploy to IONOS Webspace

on:
  push:
    branches:
      - main   # run whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload site to IONOS via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          password: ${{ secrets.IONOS_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: ${{ secrets.IONOS_REMOTE_PATH }}
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.DS_Store
            **/README.md